### PR TITLE
182 legend size

### LINKED ISSUE #182: Legends are not fully shown AND plotting area shrinks with increasing entries.
Please find a solution for auto-sizing or auto line breaks.

ALSO:
The plotting area should always be of same size.

Here an example:
013_plotTimeProfile

### PR DESCRIPTION
**Pull request by pchelle**
Fixes #182 
Algorithm tries to fit legend caption in reasonable boundaries
First reducing font size, then breaking long lines. If legend shrinks plot, set legend within plot and not above.
I set some values arbitrarily for the algorithm options, but we can update them.

### CODE REVIEW

**Comment by Yuri05** [comment]
Just created a report with this proposed change of legends.
[output.pdf](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3425776/output.pdf)

@pchelle Please rollback this change - it look much worse than before. 
* Legends are cut off (even worse than before)
* LEgend plots and plots are displayed on different pages in report. Maybe markdown joiner could handle it properly, but even then: new legends just do not look good

@msevestre FYI
grafik

**Comment by pchelle** [comment]
Is it again because the settings on my computer are different ?
This was what the legend looked like on my side:
001_legendPopulationTimeProfile

**Comment by pchelle** [comment]
Before rolling back, I have tested different possibilities for this feature.
I noticed that the saveas is not optimal since we have to set everything else but the legend invisible first and then redefine the plot area to save the legend.
Consequently, I have committed a version with getframe that gives an image snapshot of a specific area of the plot (here the legend area). So we get only the legend and no white space around.
Can you let me know if it works ? If not, I will revert to legend + plot.
Here is what I obtain from my side: 
001_legendTimeProfile


As an alternative way, we can export the legend as markdown table. But I would need a way to parse the legend symbols and colours the right way to the table.

**Comment by Yuri05** [comment]
@pchelle latest commit does not work at all.
```
>> Problem04_QualificationWorkflow
WARNING: In initializeQualificationWorkflow, Reset existing Output RE folder "C:\Problem_04\re_output" 

INFO: C:\Problem_04\re_input\report-configuration-plan.json was extracted successfully
ERROR: Unit h extracted from path ﻿"h(1) [h]" is not listed
Error using strimPath (line 26)
Unit h extracted from path ﻿"h(1) [h]" is not listed

Error in loadObservationscsv (line 32)
[timePath, timeUnit] = strimPath(timePathList);

Error in initializeQualificationWorkflow (line 95)
            ObservedDataSets(i) = loadObservationscsv(fullfile(REInput_path,
            ConfigurationPlan.ObservedDataSets{i}.Path),...

Error in Problem04_QualificationWorkflow (line 28)
[WSettings, ConfigurationPlan, TaskList, ObservedDataSets] = initializeQualificationWorkflow(jsonFile, REInput_path,
REOutput_path);

```

**Comment by Yuri05** [comment]
@pchelle 
still doesn't work at all
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/226#issuecomment-514623365

**Comment by pchelle** [comment]
That's strange. 
The error seems related to loadObservations ? but I don't think I have changed anything around that function.

**Comment by Yuri05** [comment]
@pchelle 
https://github.com/pchelle/Reporting-Engine/blob/f033d299f1ff6b442185554b98afa504280f642b/src/code/qualification/plotQualificationPKRatio.m#L133 is not even a valid Matlab code

When I fix this and try with RE input from https://github.com/Incei/test/tree/master/re_input (but replace the report configuration plan with the attached one [report-configuration-plan.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3427789/report-configuration-plan.zip)),
I get a lot of Warnings/Errors like below and those legends are not displayed at all.
Other legends are still cut off, but not as much as before.

```
ERROR: Error in TimeProfile plot 7 "Time Profile Analysis". 
 The specified rectangle is not fully contained within the figure. MATLAB no longer supports this capability. 
  In runQualificationWorkflow (line 119)
  In Problem04_QualificationWorkflow (line 35) 
```

here the pdf
[output.pdf](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3427817/output.pdf)

**Comment by pchelle** [comment]
I reverted the code to have legend and plot in the same figure; and fixed the bracket misplacement.
The error above meant that the legend caption was still bigger than the plot frame so the snapshot of the legend could not be performed. Looking at the pdf, it was not optimal as well this way since the figures are split they might be plotted on different pages.

**Pull request merged**
