### PR TITLE
 Fixes #234 Combine md-output of markdown-joiner into a single md 

### LINKED ISSUE #234: Combine md-output of markdown-joiner into a single md

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

**Review by msevestre — COMMENTED** [review]
These changes do not belong in the reporting engine whatsoever. Rather it should have been implemented in the markdown joiner as additional output

**Comment by Yuri05** [comment]
>These changes do not belong in the reporting engine whatsoever. Rather it should have been implemented in the markdown joiner as additional output

Sure. However at the moment we need a shortterm solution for the upcoming Qualification workshop in 10 days.

**Comment by msevestre** [comment]
Please create an issue in mardown-joiner referencing this PR explaining what needs to be done. Hard to tell looking at the implementation but it seems that some funky stuff is happening

Also please make sure that people are aware in this workshop that this is a temp solution

**Comment by Yuri05** [comment]
>Please create an issue in mardown-joiner referencing this PR explaining what needs to be done. Hard to tell looking at the implementation but it seems that some funky stuff is happening

@Incei Your task ;)

**Comment by msevestre** [comment]
Please make sure this is done asap because it will be forgotten

**Comment by Incei** [comment]
Done, i hope this is sufficient :), 

[https://github.com/Open-Systems-Pharmacology/markdown-joiner/issues/32](https://github.com/Open-Systems-Pharmacology/markdown-joiner/issues/32)

**Pull request merged**
